services:
  member1:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: member1
    container_name: member1
    networks:
      cluster_net:
        aliases:
          - member1

  member2:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: member2
    container_name: member2
    networks:
      cluster_net:
        aliases:
          - member2

  member3:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: member3
    container_name: member3
    networks:
      cluster_net:
        aliases:
          - member3

networks:
  cluster_net:
    driver: bridge
